POST http://localhost:8080/api/auth/signup-admin
Content-Type: application/json

{
  "username": "admin@budgettracker.com",
  "email": "admin@budgettracker.com",
  "password": "admin123",
  "firstName": "Admin",
  "lastName": "User",
  "currency": "INR"
}